/**
 * @file
 *
 * Tools to automate the testing of test samples.
 *
 * (automatically generated by metasrc/generate_test_samples.py)
 *
 */
 
#ifndef TEST_SAMPLES_H
#define TEST_SAMPLES_H

#include <stdint.h>

/** 
 * @struct v2f_test_sample_t
 * 
 * Represent all needed information about a test sequence.
 */
typedef struct {
    /// Path to the file with data
    char const *const path;
    /// Optional information about the sample
    char const *const description;
    /// Number of bytes available in the file
    uint32_t const bytes;
} v2f_test_sample_t;

/// Test sample constants
enum {
    /// Number of samples available for testing.
	V2F_C_TEST_SAMPLE_COUNT = 8
};

/// List of all v2f_test_sample_t instances. 
extern v2f_test_sample_t all_test_samples[V2F_C_TEST_SAMPLE_COUNT];

#endif /* TEST_SAMPLES_H */
